import type { Alert, Event, Place } from '@spotlive/types';

export const demoPlaces: Place[] = [
  {
    id: 'place-1',
    ownerId: 'user-1',
    name: 'Parque El Poblado',
    description: 'Punto de encuentro con eventos al aire libre.',
    category: 'park',
    city: 'Medellin',
    location: '-75.5674,6.2099',
    isVerified: true,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'place-2',
    ownerId: 'user-2',
    name: 'Plaza Botero',
    description: 'Zona cultural con alto flujo peatonal.',
    category: 'square',
    city: 'Medellin',
    location: '-75.5685,6.2518',
    isVerified: true,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'place-3',
    ownerId: 'user-3',
    name: 'Jardin Botanico',
    description: 'Espacio verde para experiencias culturales.',
    category: 'garden',
    city: 'Medellin',
    location: '-75.5712,6.2682',
    isVerified: true,
    isDeleted: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

const now = Date.now();

export const demoEvents: Event[] = [
  {
    id: 'event-1',
    ownerId: 'user-1',
    placeId: 'place-1',
    title: 'Sunset DJ Session',
    description: 'Sesion en vivo con DJs locales y artistas emergentes.',
    category: 'music',
    status: 'live',
    startAt: new Date(now - 15 * 60_000).toISOString(),
    endAt: new Date(now + 90 * 60_000).toISOString(),
    priceMin: 0,
    priceMax: 0,
    isDeleted: false,
    createdAt: new Date(now - 2 * 60 * 60_000).toISOString(),
    updatedAt: new Date(now - 10 * 60_000).toISOString(),
  },
  {
    id: 'event-2',
    ownerId: 'user-2',
    placeId: 'place-2',
    title: 'Mercado Nocturno Creativo',
    description: 'Emprendimientos locales, arte y comida urbana.',
    category: 'market',
    status: 'approved',
    startAt: new Date(now + 60 * 60_000).toISOString(),
    endAt: new Date(now + 4 * 60 * 60_000).toISOString(),
    priceMin: 0,
    priceMax: 0,
    isDeleted: false,
    createdAt: new Date(now - 3 * 60 * 60_000).toISOString(),
    updatedAt: new Date(now - 20 * 60_000).toISOString(),
  },
  {
    id: 'event-3',
    ownerId: 'user-3',
    placeId: 'place-3',
    title: 'Cine al Parque',
    description: 'Proyeccion al aire libre para familias.',
    category: 'art',
    status: 'pending',
    startAt: new Date(now + 24 * 60 * 60_000).toISOString(),
    endAt: new Date(now + 27 * 60 * 60_000).toISOString(),
    priceMin: 0,
    priceMax: 0,
    isDeleted: false,
    createdAt: new Date(now - 30 * 60_000).toISOString(),
    updatedAt: new Date(now - 30 * 60_000).toISOString(),
  },
  {
    id: 'event-4',
    ownerId: 'user-4',
    placeId: 'place-1',
    title: 'Batalla de Freestyle',
    description: 'Competencia abierta de freestyle en tarima central.',
    category: 'other',
    status: 'pending',
    startAt: new Date(now + 36 * 60 * 60_000).toISOString(),
    endAt: new Date(now + 39 * 60 * 60_000).toISOString(),
    priceMin: 0,
    priceMax: 0,
    isDeleted: false,
    createdAt: new Date(now - 20 * 60_000).toISOString(),
    updatedAt: new Date(now - 20 * 60_000).toISOString(),
  },
];

export const demoAlerts: Alert[] = [
  {
    id: 'alert-1',
    reporterId: 'user-10',
    placeId: 'place-1',
    eventId: 'event-1',
    type: 'parking_full',
    message: 'Parqueadero principal lleno.',
    location: '-75.5674,6.2099',
    expiresAt: new Date(now + 25 * 60_000).toISOString(),
    isDeleted: false,
    createdAt: new Date(now - 5 * 60_000).toISOString(),
    updatedAt: new Date(now - 5 * 60_000).toISOString(),
  },
  {
    id: 'alert-2',
    reporterId: 'user-11',
    placeId: 'place-2',
    type: 'road_closure',
    message: 'Cierre temporal por montaje de tarima.',
    location: '-75.5685,6.2518',
    expiresAt: new Date(now + 45 * 60_000).toISOString(),
    isDeleted: false,
    createdAt: new Date(now - 3 * 60_000).toISOString(),
    updatedAt: new Date(now - 3 * 60_000).toISOString(),
  },
];

export const placeCoordinates: Record<string, { longitude: number; latitude: number }> = {
  'place-1': { longitude: -75.5674, latitude: 6.2099 },
  'place-2': { longitude: -75.5685, latitude: 6.2518 },
  'place-3': { longitude: -75.5712, latitude: 6.2682 },
};
